namespace: pravic
name: pravic
version: 0.0.1
readme: README.md
description: An experimental project intended to explore how Ansible could be used to manage cloud-based resources in a more declarative way.
authors:
  - Ansible (https://github.com/ansible)
license_file: LICENSE
repository: https://github.com/ansible-collections/pravic
homepage: https://github.com/ansible-collections/pravic
issues: https://github.com/ansible-collections/pravic/issues
