name: CI
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - synchronize
      - closed
    branches:
      - main
      - stable-*
    tags:
      - '*'

jobs:
  linters:
    uses: ansible-network/github_actions/.github/workflows/tox-linters.yml@main